name: "hm2mqtt"
version: "1.2.1"
slug: "hm2mqtt"
description: "Connect Hame energy storage devices to Home Assistant via MQTT"
url: "https://github.com/kleimj1/hm2mqtt"  # <-- DEINE REPO
image: "ghcr.io/kleimj1/hm2mqtt-addon"     # <-- DEIN IMAGE
arch:
  - armv7
  - aarch64
  - amd64
init: false
startup: application
boot: auto
services:
  - mqtt:need
hassio_api: true
hassio_role: default

options:
  pollingInterval: 60
  responseTimeout: 30
  enableCellData: true              # <-- Falls du Zellspannungen aktivieren willst
  enableCalibrationData: false
  enableExtraBatteryData: false
  devices:
    - deviceType: "HMG"
      deviceId: "device-mac-address"

schema:
  mqtt_uri: str?
  pollingInterval: int?
  responseTimeout: int?
  enableCellData: bool
  enableCalibrationData: bool
  enableExtraBatteryData: bool
  debug: bool?
  devices:
    - deviceType: str
      deviceId: str
