name: Build & Push hm2mqtt Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      platform:
        required: true
        type: string
      base:
        required: false
        type: string
        default: ""
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      build-args:
        required: false
        type: string
        default: ""
      image-suffix:
        required: true
        type: string
      digest-prefix:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (labels only)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ github.repository }}
          tags: |
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platform }}
          push: true
          tags: |
            ${{ inputs.registry }}/${{ github.repository }}:latest
            ${{ inputs.registry }}/${{ github.repository }}${{ inputs.image-suffix }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_ENV=production
            ${{ inputs.build-args }}
            BASE=${{ inputs.base }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
